[package]
name = "gauge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
serde = { version="1.0.159", features = ["derive"] }
serde_json = "1.0.95"
systemstat = "0.2.3"
